from flask import jsonify, g
from flask_restful import Resource, reqparse

from models.models import auth

parser = reqparse.RequestParser()


# authenticate via username/pass or valid api-token
class Tokens(Resource):
    """
        This class is responsible for generating new tokens for sellers.
        A new token can be generated by an existing valid token or the combination of
        username and password
    """

    @auth.login_required
    def get(self):
        """
        :return: returns a valid token with with specified/default life
        """
        token = g.user.generate_auth_token()
        return jsonify({'token': token.decode('ascii')})
